In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances
from sklearn.preprocessing import StandardScaler
from scipy.spatial.distance import hamming

In [2]:
def get_cont_cat(dataframe, var_type):
    '''
    Function to split and return the dataframe by the variable type needed.
    
    I/P:
    'dataframe': whole data as a pandas dataframe
    'var_type': variable type, "cont" or "cat", string
    
    O/P:
    'dataframe': dataframe with only columns of the needed variable type
    '''
    # Convert any series to dataframe
    if not isinstance(dataframe, pd.DataFrame):
        print('ip is not dataframe')
    cont_cols = ['dist_from_uni', 'budget']
    
    if var_type == 'cont':
        return dataframe[cont_cols]
    
    elif var_type == 'cat':
        return dataframe.drop(labels = cont_cols, axis = 1)
    
    else: raise ValueError('Variable type should be either "cont" or "cat"')

In [3]:
def get_cont_dist(person, database, metric):
    
    '''
    Function that returns a distance matrix for continuous features of the data.
    Feature normalization happens in here.
    I/P:
    'person': 1 x 3 numpy array of 1 person
    'database': (total data length) x 3 numpy array
    'metric': distance metric to be used for computation. One of: euclidean.
    
    O/P:
    'distance_matrix': 1 x (total data length) numpy array of distances
    '''
#     print('sdkfjsdkf')

    to_std = np.vstack((person, database))
    
    all_std = StandardScaler().fit_transform(to_std)
    person_std = all_std[0,:].reshape(1,-1)
    database_std = all_std[1:,:]
    
    if metric == 'euclidean':
        cont_distance_matrix = euclidean_distances(person_std, database_std)
        return cont_distance_matrix

In [4]:
def get_cat_dist(person, database, metric):
    '''
    Function that returns a distance matrix for categorical features of the data.
    I/P:
    'person': 1 x 3 numpy array of 1 person
    'database': (total data length) x 3 numpy array
    'metric': distance metric to be used for computation. One of: hamming
    
    O/P:
    'distance_matrix': 1 x (total data length) numpy array of distances
    '''
    cat_distance_matrix = []
    if metric == 'hamming':
        for index, c_row in database.iterrows():
            cat_distance_matrix.append(hamming(person, c_row))
    return(np.array(cat_distance_matrix))

In [5]:
def findRoommate(new_person, database, n_roommates, alpha, beta):
    # Split data by gender to reduce computations
    database_g = database[database['Gender'] == new_person.iloc[0]['Gender']]
#     print(len(database_g))
    name_g = [name_list[i] for i in list(database_g.index)]
#     print(name_g)

    # Split new datapoint into continuous and categorical sets
    new_person_cont = get_cont_cat(new_person, 'cont')
    new_person_cat = get_cont_cat(new_person, 'cat')
    
#     print(new_person_cat.shape, new_person_cont.shape)
    
    # Split database into continuous and categorical sets
    database_cont = get_cont_cat(database_g, 'cont')
    database_cat = get_cont_cat(database_g, 'cat')
    
#     print(database_cat.shape, database_cont.shape)
    
    
    # Get distances for both continuous and categorical sets
    dist_cont = get_cont_dist(new_person_cont, database_cont, 'euclidean')
#     print(dist_cont.shape, np.argsort(dist_cont))
    
    

    dist_cat = get_cat_dist(new_person_cat, database_cat, 'hamming')
    
#     print(dist_cont + dist_cat)
    # Create final distance matrix of weighted average
    # Have to experiment with different alpha(cont_coeff) and beta(cat_coeff)
    # We good till here
    final_dist = alpha*dist_cont + beta*dist_cat
#     print(final_dist)
    # Sort the distance matrix to get top n roommates
    top_n_matches = np.argsort(final_dist)[0][1 : n_roommates + 1]
    print(top_n_matches)
    print(list(name_g[j] for j in top_n_matches))

In [2]:
def normalize(df, features):
    result = df.copy()
    for feature_name in features:
        max_value = df[feature_name].max()
        min_value = df[feature_name].min()
        result[feature_name] = ((df[feature_name] - min_value) / (max_value - min_value))*2-1
    return result

In [3]:
meta_data = pd.read_csv('../data/roommates2.csv')

In [4]:
meta_data.columns

Index(['No', 'Uni', 'Email address', 'Gender', 'Last Name', 'First Name',
       'Smoking', 'Alcohol', 'Nationality', 'School', 'Major', 'Habit',
       'Roommate', 'budget', 'dist_from_uni', 'school_label'],
      dtype='object')

In [5]:
meta_data = meta_data.drop(labels=['Uni', 'Email address', 'No', 'Last Name', 'First Name', 'Nationality', 'School', 'Major'], axis=1)

In [6]:
meta_data

,Gender,Smoking,Alcohol,Habit,Roommate,budget,dist_from_uni,school_label
0,0,1,1,1,1,1000,5.0,0
1,0,1,0,0,1,1100,2.5,1
2,1,0,0,1,1,1300,2.0,1
3,0,1,0,1,1,1600,3.0,2
4,0,0,0,0,1,1500,3.3,3
...,...,...,...,...,...,...,...,...
3485,1,0,1,0,1,1600,2.0,4
3486,0,1,1,1,1,1650,3.5,17
3487,1,1,0,0,1,1800,8.0,3
3488,1,0,1,0,1,1100,4.5,10
3489,0,1,0,1,1,1300,1.0,3

In [7]:
features = ['budget', 'dist_from_uni']
normalized_data = normalize(meta_data, features)

In [8]:
normalized_data

,Gender,Smoking,Alcohol,Habit,Roommate,budget,dist_from_uni,school_label
0,0,1,1,1,1,-1.000000,0.142857,0
1,0,1,0,0,1,-0.866667,-0.571429,1
2,1,0,0,1,1,-0.600000,-0.714286,1
3,0,1,0,1,1,-0.200000,-0.428571,2
4,0,0,0,0,1,-0.333333,-0.342857,3
...,...,...,...,...,...,...,...,...
3485,1,0,1,0,1,-0.200000,-0.714286,4
3486,0,1,1,1,1,-0.133333,-0.285714,17
3487,1,1,0,0,1,0.066667,1.000000,3
3488,1,0,1,0,1,-0.866667,0.000000,10
3489,0,1,0,1,1,-0.600000,-1.000000,3

In [9]:
test_person = normalized_data.iloc[0]

In [10]:
test_person

Gender           0.000000
Smoking          1.000000
Alcohol          1.000000
Habit            1.000000
Roommate         1.000000
budget          -1.000000
dist_from_uni    0.142857
school_label     0.000000
Name: 0, dtype: float64

In [11]:
x = test_person
dist_list = []
for i in range(normalized_data.shape[0]):
    y = normalized_data.iloc[i]
    dist = np.sqrt(np.sum([(a-b)*(a-b) for a, b in zip(x, y)]))
    dist_list.append(dist)
# dist_list

In [13]:
sorted(dist_list)[:10]

[0.0,
 0.0,
 0.9458825918426771,
 0.9458825918426771,
 0.9831228876620145,
 1.0,
 1.0400156984686455,
 1.0400156984686455,
 1.0400156984686455,
 1.0400156984686455]

In [19]:
normalized_data

,Gender,Smoking,Alcohol,Habit,Roommate,budget,dist_from_uni,school_label
0,0,1,1,1,1,-1.000000,0.142857,0
1,0,1,0,0,1,-0.866667,-0.571429,1
2,1,0,0,1,1,-0.600000,-0.714286,1
3,0,1,0,1,1,-0.200000,-0.428571,2
4,0,0,0,0,1,-0.333333,-0.342857,3
...,...,...,...,...,...,...,...,...
3485,1,0,1,0,1,-0.200000,-0.714286,4
3486,0,1,1,1,1,-0.133333,-0.285714,17
3487,1,1,0,0,1,0.066667,1.000000,3
3488,1,0,1,0,1,-0.866667,0.000000,10
3489,0,1,0,1,1,-0.600000,-1.000000,3

In [47]:
# K-Means
from sklearn.cluster import KMeans
n_clusters = int(meta_data.shape[0] / 10)
km = KMeans(n_clusters = n_clusters
           )
mat = normalized_data.values
km.fit(mat)
# Get cluster assignment labels
labels = km.labels_
# Format results as a DataFrame
results = pd.DataFrame([normalized_data.index,labels]).T

In [48]:
results

         0    1
0        0   69
1        1   86
2        2  198
3        3    6
4        4   43
...    ...  ...
3485  3485   77
3486  3486   57
3487  3487  282
3488  3488  228
3489  3489  335

[3490 rows x 2 columns]

In [103]:
results[results[1]==results[1][0]]

         0   1
0        0  69
364    364  69
1044  1044  69
1122  1122  69
1648  1648  69
2144  2144  69

In [104]:
# KNN
# from sklearn.neighbors import KNeighborsClassifier
# classifier = KNeighborsClassifier(n_neighbors=5)
# classifier.fit(X_train, y_train)

In [97]:
# cosine similarity
from sklearn.metrics.pairwise import cosine_similarity
test_person = normalized_data.iloc[0]
cs_list = []
for i in range(normalized_data.shape[0]):
    cs = np.min(cosine_similarity([test_person, normalized_data.iloc[i]]))
    cs_list.append(cs)
cs_list

[1.0000000000000002,
 0.6155402517746794,
 0.5051754582400932,
 0.521208738844587,
 0.17922794487477398,
 0.1999963785501523,
 0.1221179499408405,
 0.2995629578652558,
 0.23991508040392964,
 0.20927053683778565,
 0.5673911317380161,
 0.6860765465784374,
 0.21597917154983914,
 0.18300380247989123,
 0.4922171239114316,
 0.32292769381481934,
 0.08740472332889541,
 0.09395200092858867,
 0.13300295535850248,
 0.09033812802602269,
 0.30931200448771096,
 0.09475426502019338,
 0.11942657930457069,
 0.5516072467156634,
 -0.001553045475413456,
 0.10188000848454466,
 0.08190911870671226,
 0.024833703843272673,
 0.22971608228446722,
 0.20927053683778565,
 0.10401083892934829,
 0.13882111503555827,
 0.05678546652020564,
 0.8434347122457899,
 0.09791688735812476,
 0.1504462041343757,
 0.023706590394559787,
 0.0951444407683182,
 0.07627905557850198,
 0.09200970765603807,
 0.051241384240921124,
 0.19503575564490427,
 0.13361642696492532,
 0.18526495282864058,
 0.03997818964611819,
 0.09893225810803907,
 0.10817922946728872,
 0.6664466934746514,
 0.15104641809963126,
 0.08841127522780923,
 0.08829043783546699,
 0.08829043783546699,
 0.09850749369024019,
 0.5251914517705937,
 0.14747941898891148,
 0.06796319104697655,
 0.10889882345461017,
 0.08841127522780923,
 0.34169211246829684,
 0.09850749369024019,
 0.5606783079576969,
 0.08841127522780923,
 0.014098368233470587,
 0.08787426593690015,
 0.1339799677649864,
 0.06481923804719182,
 0.0861221761725548,
 0.6111989494904287,
 0.1363749333466853,
 0.3275156699862976,
 0.23186994752276469,
 0.14650200189506685,
 0.33989628590371346,
 0.08328876917230109,
 0.07678570087370284,
 -0.010772739386501454,
 0.3791969891852251,
 0.13008037026062966,
 0.08393268890018735,
 0.14897308439542994,
 0.06569066427981794,
 0.09740568721555655,
 0.2800250792518687,
 0.160061700927973,
 0.07707428077973737,
 0.783852779797573,
 0.0806109032091311,
 0.14598499491881325,
 0.2877582922108108,
 0.10474872942317018,
 0.07626932680881555,
 0.07380053732150661,
 0.3582891592468819,
 0.09326355285306803,
 0.23050555684110804,
 0.32766250278666387,
 0.03703956459839533,
 0.14650636676685422,
 0.5734339024144959,
 0.10474872942317018,
 0.10756358223405516,
 0.10731090737670555,
 0.08558012159619237,
 0.08747070207034524,
 0.3338467773043234,
 0.15174368166544144,
 0.5075647261379699,
 0.055681296613609,
 0.12527053799077503,
 0.10437946814580823,
 0.1279983861728918,
 0.04061722724387338,
 0.05766661690991679,
 0.18262731278461286,
 0.1999963785501523,
 0.17655970515600142,
 0.031313716112982,
 0.08321067701280949,
 0.4209175542850984,
 0.3132713527757511,
 0.3756066388992368,
 0.07923764854896735,
 0.11736319547340812,
 0.6852242522254567,
 0.10786601712813038,
 0.043805325320881335,
 0.059639286434740035,
 0.3576596266474504,
 0.06915722850836958,
 0.28660312624137624,
 0.11392372803836079,
 0.14357764694406366,
 0.08393268890018735,
 0.07707428077973737,
 0.557879623930421,
 0.126674558729157,
 0.11912924283340533,
 0.05266133713542284,
 0.05457456789547986,
 0.10525638236599988,
 0.05349384167238644,
 0.10597684266147786,
 0.12527053799077503,
 0.1624365391909457,
 0.30563920738036066,
 0.15674877574230311,
 0.5606783079576969,
 0.09104139504847143,
 0.1280350206205846,
 0.08218716412063473,
 0.13835473155395933,
 0.06522080993573028,
 0.03672957743334773,
 0.10437946814580823,
 0.5223589694572991,
 0.07753620384753743,
 0.13502691698303806,
 0.08829043783546699,
 0.557879623930421,
 0.6955606985430541,
 0.05752585992208171,
 0.557879623930421,
 0.4108558573064062,
 0.11718536127730735,
 0.17784753233727355,
 0.49240227989441093,
 0.08218716412063473,
 0.4142092038307649,
 0.0627843156827507,
 0.3888091837075367,
 0.0865429780629744,
 0.045825398940027656,
 0.08403648185459772,
 0.06823780442818794,
 0.19634050819757198,
 0.15176516460438047,
 0.06193508163759544,
 0.036977947307495936,
 0.11940999607276295,
 0.09312174055542541,
 0.18512905679536096,
 0.1005095604264746,
 0.6155402517746794,
 0.07796366842211408,
 0.061231616585359395,
 0.11942657930457069,
 0.22971608228446722,
 0.6816820874329419,
 0.12279508457530584,
 0.04656199050976187,
 0.2995629578652558,
 0.10731090737670555,
 0.27739883955605055,
 0.5251914517705938,
 0.17836054020978837,
 0.12173833774421498,
 0.0726055209552101,
 0.28306950330128905,
 0.234033843278514,
 0.13835473155395933,
 0.04739538638774633,
 0.08328876917230109,
 0.5451944799839984,
 0.04331501234133936,
 0.11869534583136536,
 0.03703956459839533,
 0.21378648960517072,
 0.1889407403843461,
 0.08020595342178313,
 0.3781425545678703,
 0.8554505757331003,
 0.0733012332960202,
 0.06183417626037439,
 0.4274814142318785,
 0.15031763403531476,
 0.7020717960782046,
 0.05888880236959523,
 0.08230375184677446,
 0.6215650455546075,
 0.58586934572499,
 0.07881502456504672,
 0.1766207880164515,
 0.15909444965848615,
 0.06910159641439986,
 0.13835473155395933,
 0.10305540414679167,
 0.18857649798114248,
 0.7651638514867657,
 0.056972252855580476,
 0.5188439814876014,
 0.21706489271608528,
 0.11354828698130325,
 0.8857964689616405,
 0.10454792857043843,
 0.08189314826911495,
 0.20769575801727846,
 0.10889882345461017,
 0.5013551477432543,
 0.10074820621917553,
 0.08459137355114103,
 0.054836641232894806,
 0.23186994752276469,
 0.1335377024775508,
 0.09707868535312651,
 0.19019385332156696,
 0.05879336575131055,
 0.0806109032091311,
 0.3849117848872333,
 0.14048713385988343,
 0.2941193996825156,
 0.09543952115414817,
 0.08683950519946684,
 0.175930588650972,
 0.02313230949878005,
 0.24472241561853103,
 0.7651638514867657,
 0.17414449130426163,
 0.09652263065979387,
 0.06073160513263005,
 0.24992951692474766,
 0.19130974016162375,
 0.09347639173428557,
 0.4142092038307649,
 0.859220530430129,
 0.7238624523609379,
 0.10255445673679796,
 0.3332059626000356,
 0.10050249985313296,
 0.05357261080612974,
 0.06469403712712112,
 0.066989906437147,
 0.2674401751189386,
 0.07234488530662571,
 0.08072114491596956,
 0.14580106323164813,
 0.043261519503054444,
 0.1398288144892333,
 0.03662265252819054,
 0.3610240691181117,
 0.08328876917230109,
 0.11158716007368416,
 0.1378060614833674,
 0.24490238610343434,
 0.07785682817156933,
 0.1456631208856364,
 0.07029959786485523,
 0.21985270508385518,
 0.19262268177765413,
 0.10889882345461017,
 0.0655205987832247,
 0.1774912961159316,
 0.05646323262594756,
 0.16648498112154322,
 0.15155179145445,
 0.06073160513263005,
 0.049039817832364274,
 0.10139050246585919,
 0.25492441658229265,
 0.11042967125181766,
 0.127118879814688,
 0.04405057214238356,
 0.12460915040733941,
 0.07374654350572744,
 0.379278089455087,
 0.025356538694576734,
 0.6580389044100772,
 0.030076346955767008,
 0.11634597858177527,
 0.06570037577910029,
 0.06910159641439986,
 0.1280350206205846,
 0.03672957743334773,
 0.15064639333211646,
 0.05507225424667315,
 0.027158619849564202,
 0.1274420676680209,
 0.30536568888823046,
 0.12265534938753203,
 0.12183786174050544,
 0.7496684711103935,
 0.20016948603152393,
 0.08393268890018735,
 0.5943715039184528,
 0.5527027854502823,
 0.32671793802007865,
 0.32315392484536276,
 0.29627396825619895,
 0.11158716007368416,
 0.39902534229192177,
 0.2208766855273399,
 0.11108716724104577,
 0.09849995039322627,
 0.14484386525981385,
 0.05375531582732917,
 0.5982617743096056,
 0.10597684266147786,
 0.0763954055669441,
 0.21597917154983914,
 0.05116270710985138,
 0.18207700163193793,
 0.04591198896286247,
 0.04193860749193317,
 0.07154660610180966,
 0.29040670790599254,
 0.3068521805767929,
 0.06505315614353899,
 0.1518057032925779,
 0.026560901005615076,
 0.24252918104762283,
 0.06862346969454719,
 0.7167236346784112,
 0.8554505757331003,
 0.58586934572499,
 0.16479541119518026,
 0.11039548903629816,
 0.09740568721555655,
 0.1090039663319796,
 0.09562262926376933,
 0.13555661927037502,
 0.6155402517746794,
 0.0757871690082013,
 0.1669981975671584,
 0.04061722724387338,
 0.10249145562560008,
 0.9057560942362506,
 0.24685134850520096,
 0.172054250201052,
 0.06525607423543026,
 0.11789280334818077,
 0.16479541119518026,
 0.08729952465728394,
 0.0866335749301638,
 0.13300295535850248,
 0.05802493137064928,
 0.067558838034856,
 0.09828475422560276,
 0.15891275762394316,
 0.18026036628309425,
 0.11893147525121407,
 0.10591822079588575,
 0.07744054201751847,
 0.37700223333899985,
 0.12183786174050544,
 0.20712044590662976,
 0.16136705614679803,
 0.23715054392148993,
 0.03858652244330412,
 0.11158716007368416,
 0.13522087302682992,
 0.10993393806021985,
 0.24685134850520096,
 -0.0014473257799452173,
 0.5109939965801106,
 0.05917929425096693,
 0.09033812802602269,
 0.11912924283340533,
 0.5751597257550616,
 0.15104641809963126,
 0.17061027411182578,
 0.15103610497740766,
 0.040766889450979414,
 0.1442200591771154,
 0.20016948603152393,
 0.07209853139063846,
 0.18300380247989123,
 0.11319565799818573,
 0.38939791767637955,
 0.7167236346784112,
 0.11339783879386482,
 0.11893147525121407,
 0.07117445247356312,
 0.04669523426874081,
 0.2501005578433578,
 0.04856734220371215,
 0.2173968140144978,
 0.0979448040295008,
 0.0302483239815634,
 0.19634050819757198,
 0.35844554999754036,
 0.09707868535312651,
 0.14650200189506685,
 0.5934959349593498,
 0.06569066427981794,
 0.6664466934746514,
 0.5935316795894522,
 0.14381331300461167,
 0.10305540414679167,
 0.0907239089773903,
 0.35478314523011495,
 0.05432344791736864,
 0.19384608456122934,
 0.4645718123990622,
 0.15104641809963126,
 0.10182869803619445,
 0.09707868535312651,
 0.14804142687059132,
 0.6118137802073297,
 0.09336815937954321,
 0.10597684266147786,
 0.5336354514426224,
 0.3163101118709986,
 0.16310913515102668,
 0.5943715039184528,
 0.7074107315551632,
 0.18526495282864058,
 0.11014513002815791,
 0.10067310034973122,
 0.21535224372734096,
 0.1095673845807469,
 0.05442859086518786,
 0.11146449409501216,
 0.4735998437642612,
 0.06103484989236869,
 0.048347893972458825,
 0.16125608125837995,
 0.39028403286888325,
 0.13882111503555827,
 0.09225457023646004,
 0.10538213414210051,
 0.038840668871161874,
 0.11285123889680937,
 0.38071308871388404,
 0.4630485670405553,
 0.07673904923584858,
 0.12173402293452708,
 0.1894077449827984,
 0.17320047882847098,
 0.025209466776500856,
 0.24472241561853103,
 0.06725361294833498,
 0.1573657530701937,
 0.12849240277263943,
 0.13725968687339699,
 0.06061053079382576,
 0.24923453328839593,
 0.10255445673679796,
 0.04839861804941163,
 0.19294940893254936,
 0.17655970515600142,
 0.07122849452095252,
 0.06937044567767901,
 0.08514765443334456,
 0.19160345224999767,
 0.07395284563095866,
 0.16479541119518026,
 0.09762429381125241,
 0.06754437825673508,
 0.06505315614353899,
 0.08205104112519224,
 0.09225457023646004,
 0.5251914517705938,
 0.1502299017493975,
 0.2668389320008038,
 0.4108558573064062,
 0.21900116471045528,
 0.07029959786485523,
 0.046100391077172224,
 0.04661522939276113,
 0.8857964689616405,
 0.46516229722304936,
 0.06212745107122034,
 0.12265534938753203,
 0.08688338274681584,
 0.35844554999754036,
 0.2569489009545211,
 0.16441140833175208,
 0.31241258940103583,
 0.40810483258073954,
 0.09033812802602269,
 0.13351330367331324,
 0.049495078207402,
 0.12013030428895831,
 0.11968505057115401,
 0.2292376307579164,
 0.0821239137608393,
 0.1279983861728918,
 0.2800250792518687,
 -0.001553045475413456,
 0.06567018785023472,
 0.06514457113175305,
 0.21282896242613872,
 0.15103610497740766,
 0.2754959651343609,
 0.10550250850429306,
 0.4785742399621158,
 0.6412361648840972,
 0.15439366544701363,
 0.09335858742939615,
 0.30233932786011425,
 0.6632117152225616,
 0.04355210343766055,
 0.08423756171120983,
 0.13450827516981165,
 0.26735542426087855,
 0.0880946929766118,
 0.7389321588865332,
 0.07080506611957176,
 0.19146494284852303,
 0.1863577004815913,
 0.10516558210569192,
 0.12339994087911597,
 0.13522087302682992,
 0.28069671743827485,
 0.3020700097679128,
 0.04588846174065215,
 0.0733012332960202,
 0.21597917154983914,
 0.054602745376931265,
 0.09441042383657093,
 0.4095563626733778,
 0.07714505758963047,
 0.5180020052371914,
 0.1001687830780608,
 0.17753382725515227,
 0.16500399623892645,
 0.07077839696240588,
 0.12333862854033557,
 0.07398656333736127,
 0.12104574944362273,
 0.6632117152225616,
 0.14169282521398266,
 0.09837329257188708,
 0.08353003255112358,
 0.055474694253859806,
 0.47118299074168796,
 0.17784753233727355,
 0.2837341003672206,
 0.04570166998693459,
 0.06874165212668756,
 0.11912924283340533,
 0.4612525519013923,
 0.08514765443334456,
 0.23936096382564123,
 0.09104139504847143,
 0.2716256390786372,
 0.29459020779176426,
 0.09757075792521609,
 0.1250209294594969,
 0.149033995628553,
 0.07829665842936576,
 0.07188155360482014,
 0.08836237214457968,
 0.10119843882681623,
 0.8987878424486759,
 -0.0010901070131684447,
 0.0908597906348216,
 0.07996995811966039,
 0.09122368865998753,
 0.09272789395808399,
 0.09075130948749606,
 0.0763954055669441,
 0.06874165212668756,
 0.21930519045692132,
 0.18144669473019717,
 0.10050249985313296,
 0.4612525519013923,
 0.11127482366947235,
 0.39028403286888325,
 0.3582891592468819,
 0.1660318838593899,
 0.1501249870339342,
 0.13986829805613857,
 0.04591198896286247,
 0.057450729366981645,
 0.06318519692332382,
 0.04570166998693459,
 0.16700159122785124,
 0.2674401751189386,
 0.2751542699761519,
 0.6816820874329419,
 0.02513460987987884,
 0.24724128646845295,
 0.04303507865327857,
 0.0857451117554117,
 0.07937848715570538,
 0.10188000848454466,
 0.02810224222726962,
 0.1624365391909457,
 0.3396364798441537,
 0.1320875790768325,
 0.557879623930421,
 0.16558521317151248,
 0.13462253383049255,
 0.4212570496119274,
 0.09535754718114584,
 0.1488857581200284,
 0.7839764877682541,
 0.04238514468975313,
 0.2081247978030498,
 0.03905681799001781,
 0.13475760023941724,
 0.16466169726205454,
 0.09129977325486255,
 0.14018464274675987,
 0.07400462050945086,
 0.08927422170066163,
 0.3042494742440985,
 0.12089049560980598,
 0.1069725004762514,
 0.14897308439542994,
 0.11372618138996773,
 0.1962222219407752,
 0.044972346791890425,
 0.06523903300756492,
 0.10249145562560008,
 0.19201639813514465,
 0.07395284563095866,
 0.18811764750402593,
 0.07231571135773911,
 0.17414449130426163,
 0.18857649798114248,
 0.10196896452718938,
 0.08402289880226091,
 0.7067849408450959,
 0.10991855830476308,
 0.09199176998721334,
 0.11545212129201159,
 0.13835473155395933,
 0.1610743346726916,
 0.25492441658229265,
 0.04821777965415926,
 0.11762212521698148,
 0.32898718331632587,
 0.254658920180427,
 0.15479497054672664,
 0.38739003542340494,
 0.783852779797573,
 0.0727359750230761,
 0.021139975012639384,
 0.10401083892934829,
 0.39168025717182525,
 0.0826266738508038,
 0.19883682356435883,
 0.619848050636224,
 0.0978768738846771,
 0.11634597858177527,
 0.15103610497740766,
 0.25084640942549563,
 0.06665586682242212,
 0.1733134098553804,
 0.133762112836852,
 0.2668389320008038,
 0.23991508040392964,
 0.09639253854237598,
 0.09707428360059836,
 0.12339497277398156,
 0.07278629215560521,
 0.07101224539565057,
 0.07714505758963047,
 0.022212833855270047,
 0.07234488530662571,
 0.21440170941438744,
 0.10249022158783379,
 0.0634441555032409,
 0.06921544631566678,
 0.038797361235638414,
 0.11014513002815791,
 0.03238069783980808,
 0.4071651440041579,
 0.1205606735423266,
 0.20473779494379482,
 0.26368411793830554,
 0.04179785817285099,
 0.26537492868410273,
 0.6860765465784374,
 0.12460915040733941,
 0.07380053732150661,
 0.379278089455087,
 0.07981609384494777,
 0.10500097189930713,
 0.07256895616043053,
 0.11409999223177163,
 0.47920385606197574,
 0.05158009057387058,
 0.16847054332808395,
 0.8008130081300815,
 0.1624365391909457,
 0.3259093595339158,
 0.31075856511131805,
 0.27302022424966976,
 0.06624052150678494,
 0.13414556834581018,
 0.07256895616043053,
 0.06197142454769531,
 0.08514385780575605,
 0.05071099397616828,
 0.14385670787999247,
 0.11830890852043403,
 0.10500097189930713,
 0.215922902085708,
 0.066989906437147,
 0.09924765862695674,
 0.1341480961139129,
 0.11344087079966715,
 0.07965582846579693,
 0.12339994087911597,
 0.36527215102838123,
 0.08704513588589304,
 0.1046338603251352,
 0.10308287658042796,
 0.13527528206544628,
 0.04829167104903056,
 0.08078294391393978,
 0.539019616872239,
 0.1524128403659848,
 0.46516229722304936,
 0.19046427727231263,
 0.05083435720153978,
 0.1399422247360734,
 -0.003495101716077689,
 0.2972013641802584,
 0.10319308488697188,
 0.08321067701280949,
 0.1868224049193738,
 0.1029683807766412,
 0.12849240277263943,
 0.16466169726205454,
 0.6481727072600473,
 0.05474283924333876,
 0.09323525084818551,
 0.06796319104697655,
 0.8434347122457899,
 0.10083661405992632,
 0.09391653462453793,
 0.4630485670405553,
 0.10474872942317018,
 0.128076674787338,
 0.4584824880379615,
 0.033002992210491494,
 0.04348817038371729,
 0.08907565605161231,
 0.04651504027904899,
 0.084473397971791,
 0.38071308871388404,
 0.08710872652535136,
 0.1504462041343757,
 0.6417919652892325,
 0.13652728149387536,
 0.10358104298367864,
 0.07139622118440515,
 0.1945982990266557,
 0.08321067701280949,
 0.10799593837765066,
 0.09075130948749606,
 0.17509098328979456,
 0.6722968072119118,
 0.5031840109473361,
 0.12393539308142082,
 0.14183660501372902,
 0.29625682519091584,
 0.19991111289960017,
 0.07209853139063846,
 0.08683950519946684,
 0.1645288661390127,
 0.16699435932675388,
 0.15031763403531476,
 0.04331501234133936,
 0.09052647206440423,
 0.14650200189506685,
 0.05777612678315963,
 0.05958957471380887,
 0.07678570087370284,
 0.18745391737449174,
 0.1733134098553804,
 0.0978768738846771,
 0.1339799677649864,
 0.379278089455087,
 0.07340179099482726,
 0.09543952115414817,
 0.05811882610398124,
 0.13091922498577319,
 0.48526404314483546,
 0.06865915824207279,
 0.03727644057937408,
 0.0696986547805844,
 0.2587626377091208,
 0.3735801760968814,
 0.07953651745896338,
 0.1175458935774471,
 0.13462253383049255,
 0.07678570087370284,
 0.061807891980809285,
 0.04753600478353195,
 0.07400462050945086,
 0.1584194599684666,
 0.11014513002815791,
 0.08083621592547495,
 0.04163225014922603,
 0.28306950330128905,
 0.6137136368685187,
 0.4010182790651432,
 0.03727644057937408,
 0.17615374357065383,
 0.09976726996281791,
 0.1268713257307855,
 0.09850749369024019,
 0.12795030697017595,
 0.11117504394030288,
 0.38015708594095543,
 0.19404451603022194,
 0.1812718105768315,
 0.13555661927037502,
 0.7238624523609379,
 0.14890966721358692,
 0.04671508126807683,
 0.15884683338347086,
 0.15155179145445,
 0.07400462050945086,
 0.1087329600792176,
 0.45411720050870613,
 0.4328014246403676,
 0.21020667630674614,
 0.31150191409146233,
 0.09247857824741748,
 0.6664466934746514,
 0.08096979185755845,
 0.11392372803836079,
 0.04920517621702021,
 0.05928684760841,
 0.2674401751189386,
 0.4630485670405553,
 0.5180020052371914,
 0.1024819677614853,
 0.09532243649679488,
 0.7839764877682541,
 0.0978768738846771,
 0.08501829387972502,
 0.2996141560299623,
 0.7424180822227454,
 0.3888226596451112,
 0.7338030600929656,
 0.1584194599684666,
 0.11718536127730735,
 0.10796128938491252,
 0.08004451494026182,
 0.3119260588385417,
 0.04303507865327857,
 0.1598380570136504,
 0.050085108151351615,
 0.05473672634997653,
 0.2578719238890398,
 0.05357261080612974,
 0.05142695498221817,
 0.2032299667290762,
 0.21255439620176214,
 0.1124719172617351,
 0.13652728149387536,
 0.20257984035038948,
 0.045825398940027656,
 0.5934959349593498,
 0.06910159641439986,
 0.08501829387972502,
 0.7389321588865332,
 0.06411516448131296,
 0.043261519503054444,
 0.11452910541464394,
 0.8434347122457899,
 0.08353003255112358,
 0.08069841125711656,
 0.11042596318657649,
 0.3679503869418605,
 0.20860739842487636,
 0.09246114273209623,
 0.030079149485753298,
 0.08389871309958447,
 0.1024362717452781,
 0.06318519692332382,
 0.08987373679275523,
 0.018418441277803677,
 0.0770828234284285,
 0.14935314714691242,
 0.12655536402144962,
 0.07256895616043053,
 0.09651229574912913,
 0.23785488197498542,
 0.20927053683778565,
 0.09246114273209623,
 0.10038687084751867,
 0.07186122784040018,
 0.06578182290063313,
 0.17523583107047175,

In [109]:
s = np.array(cs_list)
sort_index = np.argsort(s)
print(sort_index[::-1])

[   0 2144 3392 ... 1324 1733   75]

In [107]:
normalized_data.iloc[0]

Gender           0.000000
Smoking          1.000000
Alcohol          1.000000
Habit            1.000000
Roommate         1.000000
budget          -1.000000
dist_from_uni    0.142857
school_label     0.000000
Name: 0, dtype: float64

In [111]:
normalized_data.iloc[3392]

Gender           0.000000
Smoking          1.000000
Alcohol          1.000000
Habit            1.000000
Roommate         1.000000
budget          -0.600000
dist_from_uni   -0.714286
school_label     0.000000
Name: 3392, dtype: float64

In [13]:
test_p_cont = np.array(get_cont_cat(test_person, 'cont')).reshape((1,2))
db_cont = np.array(get_cont_cat(meta_data, 'cont'))

ip is not dataframe

In [14]:
test_p_cont.shape

(1, 2)

In [15]:
euclidean_distances(test_p_cont, db_cont).shape

(1, 3490)

In [17]:
findRoommate(test_person, meta_data, 5, 1, 1)

TypeError: string indices must be integers

In [126]:
meta_data['Gender']

0       0
1       0
2       1
3       0
4       0
       ..
3485    1
3486    0
3487    1
3488    1
3489    0
Name: Gender, Length: 3490, dtype: int64